blueprint:
  name: Plugin Ocupación - Control Unificado
  description: >
    Controla el comportamiento de ocupación para una habitación o zona,  manejando sensores de movimiento, luces, climatización y estados lógicos.
  domain: automation
  input:
    tiempo_scan:
      name: Tiempo Sensor de Scanner
      description: Tiempo estimado de escáner después de la desactivación del Sensor de Movimiento
      default: 15
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
    sensor_mov:
      name: Sensor de Movimiento Principal
      description: Registra el itemId del sensor de movimiento principal
      selector:
        entity:
          domain: switch
    actuadores_on:
      name: Actuadores ON
      description: Dispositivos que encienden al pasar de libre a ocupado
      selector:
        target:
          entity:
            domain: switch
    actuadores_off:
      name: Actuadores OFF
      description: Dispositivos que se apagan al pasar de scan a libre
      selector:
        target:
          entity:
            domain: switch
    termostato:
      name: Termostato
      description: DeviceId del termostato para control de temperatura
      selector:
        entity:
          domain: climate
    setpoint_on:
      name: SetPoint ON del termostato
      description: Temperatura a establecer al pasar de libre a ocupado
      default: 24
      selector:
        number:
          min: 16
          max: 30
          unit_of_measurement: °C
    estado_plugin:
      name: Estado Plugin
      description: Auxiliar de estado del plugin
      selector:
        entity:
          domain: input_select
    estado_ocupacion:
      name: Estado Ocupacion
      description: Auxiliar de estado de ocupación
      selector:
        entity:
          domain: input_select
    modo_plugin:
      name: Modo Plugin
      description: Define si el plugin está en Auto o Apagado
      selector:
        entity:
          domain: input_select
    modo_encendido_termostato:
      name: Modo Encendido Termostato
      description: Registra (si/no) desea habilitar el termostato (no por defecto)
      selector:
        entity:
          domain: input_boolean
    modo_disparador_luces:
      name: Modo Disparador Luces
      description: Registra (si/no) desea habilitar las luces por disparo de Movimiento o Actuadores (no por defecto)
      selector:
        entity:
          domain: input_boolean

trigger:
- platform: state
  entity_id: !input estadoplugin
  from: "ocupado"
  to: "libre"
  id: plugin_libre

- platform: state
  entity_id: !input sensor_movimiento
  from: "off"
  to: "on"
  id: encender

- platform: state
  entity_id: !input sensor_movimiento
  from: "on"
  to: "off"
  for:
    seconds: 0
  id: scaner

- platform: state
  entity_id: !input sensor_movimiento
  from: "on"
  to: "off"
  for:
    minutes: 1
  id: apagar

- platform: state
  entity_id: !input estadosinternos
  from: "libre"
  to: "ocupado"
  id: libre_ocupado

- platform: state
  entity_id: !input estadosinternos
  from: "ocupado"
  to: "scan"
  id: ocupado_scan

- platform: state
  entity_id: !input estadosinternos
  from: "scan"
  to: "libre"
  id: scan_libre

- platform: state
  entity_id: !input estadoplugin
  from: "libre"
  to: "ocupado"
  id: plugin_ocupado

- platform: state
  entity_id: !input estadoplugin
  from: "ocupado"
  to: "libre"
  id: plugin_libre_2

- platform: state
  entity_id: !input switches_luces
  from: "off"
  to: "on"
  for:
    seconds: 20
  id: onSwitchDelay

condition: []

action:
- choose:
  - conditions:
    - condition: trigger
      id: encender
    - condition: state
      entity_id: !input estadosinternos
      state: "libre"
    sequence:
    - service: input_select.select_option
      target:
        entity_id: !input estadosinternos
      data:
        option: "ocupado"
    - service: input_select.select_option
      target:
        entity_id: !input estadoplugin
      data:
        option: "ocupado"
    - condition: state
      entity_id: !input modoplugin
      state: "Auto"
    - choose:
      - conditions:
        - condition: state
          entity_id: !input modo_act_on
          state: "on"
        sequence:
        - service: switch.turn_on
          target:
            entity_id: !input switches_luces
      - conditions:
        - condition: state
          entity_id: !input modo_termostato
          state: "on"
        sequence:
        - service: switch.turn_on
          target:
            entity_id: !input interruptor_termostato

  - conditions:
    - condition: trigger
      id: scaner
    - condition: state
      entity_id: !input estadosinternos
      state: "ocupado"
    sequence:
    - service: input_select.select_option
      target:
        entity_id: !input estadosinternos
      data:
        option: "scan"

  - conditions:
    - condition: trigger
      id: encender
    - condition: state
      entity_id: !input estadosinternos
      state: "scan"
    sequence:
    - service: input_select.select_option
      target:
        entity_id: !input estadosinternos
      data:
        option: "ocupado"

  - conditions:
    - condition: trigger
      id: apagar
    - condition: state
      entity_id: !input estadosinternos
      state: "scan"
    sequence:
    - service: input_select.select_option
      target:
        entity_id: !input estadosinternos
      data:
        option: "libre"
    - service: input_select.select_option
      target:
        entity_id: !input estadoplugin
      data:
        option: "libre"
    - condition: state
      entity_id: !input modoplugin
      state: "Auto"
    - service: switch.turn_off
      target:
        entity_id: !input switches_luces
    - service: switch.turn_off
      target:
        entity_id: !input interruptor_termostato

  - conditions:
    - condition: trigger
      id: plugin_libre
    sequence:
    - condition: state
      entity_id: !input modoplugin
      state: "Auto"
    - service: switch.turn_off
      target:
        entity_id: !input switches_luces
    - service: switch.turn_off
      target:
        entity_id: !input interruptor_termostato
    - service: input_select.select_option
      target:
        entity_id: !input estadosinternos
      data:
        option: "libre"
    - service: input_select.select_option
      target:
        entity_id: !input estadoplugin
      data:
        option: "libre"

  default: []
