alias: Demo PLG-Aula - ON/OFF
description: Control de ocupación basado en sensor de presencia
triggers:
- entity_id: sensor.9_in_1_multi_sensor_general_purpose
  from: "0.0"
  to: "1.0"
  for:
    seconds: 1
  id: encender
  trigger: state
- entity_id: sensor.9_in_1_multi_sensor_general_purpose
  from: "1.0"
  to: "0.0"
  for:
    seconds: 0
  id: scaner
  trigger: state
- entity_id:
  - sensor.9_in_1_multi_sensor_general_purpose
  from: "1.0"
  to: "0.0"
  for:
    hours: 0
    minutes: 5
    seconds: 0
  id: apagar
  trigger: state
- entity_id: input_select.EstadosInternos
  from: libre
  to: ocupado
  trigger: state
- entity_id:
  - input_select.EstadosInternos
  to: scan
  trigger: state
  from: ocupado
- entity_id: input_select.EstadosInternos
  from: scan
  to: libre
  trigger: state
- entity_id: input_select.estadoplugin
  from: libre
  to: ocupado
  trigger: state
- entity_id: input_select.estadoplugin
  from: ocupado
  to: libre
  trigger: state
actions:
- choose:
  - conditions:
    - condition: trigger
      id: encender
    - condition: state
      entity_id: input_select.EstadosInternos
      state: libre
    sequence:
    - data:
        option: ocupado
      target:
        entity_id:
        - input_select.EstadosInternos
        - input_select.estadoplugin
      action: input_select.select_option
    - target:
        entity_id: light.sw1_basic
      action: light.turn_on
      data: {}
    - target:
        entity_id: climate.node_4
      action: climate.turn_on
      data: {}
    - data:
        temperature: 24
        hvac_mode: cool
      target:
        entity_id: climate.node_4
      action: climate.set_temperature
    - data:
        fan_mode: Auto low
      target:
        entity_id: climate.node_4
      action: climate.set_fan_mode
  - conditions:
    - condition: trigger
      id: scaner
    - condition: state
      entity_id: input_select.EstadosInternos
      state: ocupado
    sequence:
    - data:
        option: scan
      action: input_select.select_option
      target:
        entity_id: input_select.estadosinternos
  - conditions:
    - condition: trigger
      id: encender
    - condition: state
      entity_id: input_select.EstadosInternos
      state: scan
    sequence:
    - data:
        option: ocupado
      action: input_select.select_option
      target:
        entity_id: input_select.estadosinternos
  - conditions:
    - condition: trigger
      id: apagar
    - condition: state
      entity_id: input_select.estadosinternos
      state: scan
    sequence:
    - data:
        option: libre
      target:
        entity_id:
        - input_select.EstadosInternos
        - input_select.estadoplugin
      action: input_select.select_option
    - target:
        entity_id: light.sw1_basic
      action: light.turn_off
      data: {}
    - target:
        entity_id: climate.node_4
      action: climate.turn_off
      data: {}
mode: single
