blueprint:
  name: Control de Ocupación Inteligente - Aula
  description: >
    Automatización tipo plugin para manejar ocupación en aulas con sensores de movimiento, luces, 
    termostatos e interruptores tipo scanner. Cambia automáticamente entre estados: libre, ocupado y scan.
  domain: automation
  input:
    sensores_movimiento:
      name: Sensores de movimiento
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true

    luces_a_encender:
      name: Luces al detectar ocupación
      selector:
        entity:
          domain: light
          multiple: true

    luces_scan:
      name: Luces tipo Scan
      default: []
      selector:
        entity:
          domain: light
          multiple: true

    termostatos:
      name: Termostatos a controlar
      default: []
      selector:
        entity:
          domain: climate
          multiple: true

    switches_scan:
      name: Interruptores tipo scanner
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    input_estado_interno:
      name: input_select de Estado Interno
      selector:
        entity:
          domain: input_select

    input_estado_plugin:
      name: input_select de Estado Plugin
      selector:
        entity:
          domain: input_select

trigger:
  - platform: state
    entity_id: !input sensores_movimiento
    from: "off"
    to: "on"
    for: 
      seconds: 1
    id: encender

  - platform: state
    entity_id: !input sensores_movimiento
    from: "on"
    to: "off"
    for:
      seconds: 0
    id: scaner

  - platform: state
    entity_id: !input sensores_movimiento
    from: "on"
    to: "off"
    for:
      minutes: 2
    id: apagar

  - platform: state
    entity_id: !input switches_scan
    from: "off"
    to: "on"
    for:
      seconds: 10
    id: scaner

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: encender
          - condition: state
            entity_id: !input input_estado_interno
            state: "libre"
        sequence:
          - service: input_select.select_option
            data:
              option: "ocupado"
            target:
              entity_id: 
                - !input input_estado_interno
                - !input input_estado_plugin

          - service: light.turn_on
            target:
              entity_id: !input luces_a_encender

          - service: climate.turn_on
            target:
              entity_id: !input termostatos

          - service: climate.set_temperature
            data:
              temperature: 24
              hvac_mode: cool
            target:
              entity_id: !input termostatos

          - service: climate.set_fan_mode
            data:
              fan_mode: "Auto low"
            target:
              entity_id: !input termostatos

      - conditions:
          - condition: trigger
            id: scaner
          - condition: state
            entity_id: !input input_estado_interno
            state: "ocupado"
        sequence:
          - service: input_select.select_option
            data:
              option: "scan"
            target:
              entity_id: !input input_estado_interno

      - conditions:
          - condition: trigger
            id: encender
          - condition: state
            entity_id: !input input_estado_interno
            state: "scan"
        sequence:
          - service: input_select.select_option
            data:
              option: "ocupado"
            target:
              entity_id: !input input_estado_interno

      - conditions:
          - condition: trigger
            id: apagar
          - condition: state
            entity_id: !input input_estado_interno
            state: "scan"
        sequence:
          - service: input_select.select_option
            data:
              option: "libre"
            target:
              entity_id: 
                - !input input_estado_interno
                - !input input_estado_plugin

          - service: light.turn_off
            target:
              entity_id: !input luces_a_encender

          - service: climate.turn_off
            target:
              entity_id: !input termostatos

      - conditions:
          - condition: state
            entity_id: !input input_estado_plugin
            state: "libre"
          - condition: trigger
            id: scaner
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input switches_scan

mode: single
