blueprint:
  name: Escena ON/OFF dependiente por sensor con input_boolean
  description: >
    Automatización combinada que enciende dispositivos al detectar presencia 
    y los apaga tras ausencia, controlado por un input_boolean. Incluye manejo 
    de luz, climatizador, temperatura y velocidad del ventilador.
  domain: automation
  input:
    sensor_presencia:
      name: Sensor de presencia
      selector:
        entity:
          domain: sensor
    valor_encendido:
      name: Valor de activación del sensor
      default: "1.0"
    valor_apagado:
      name: Valor de apagado del sensor
      default: "0.0"
    delay_encendido:
      name: Retardo para encender (segundos)
      default: 3
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: s
          mode: slider
    delay_apagado:
      name: Retardo para apagar (segundos)
      default: 30
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: s
          mode: slider
    luz:
      name: Luz a controlar
      selector:
        entity:
          domain: light
    clima:
      name: Climatizador a controlar
      selector:
        entity:
          domain: climate
    variable_estado:
      name: input_boolean de control
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id: !input sensor_presencia
    from: !input valor_apagado
    to: !input valor_encendido
    for:
      seconds: !input delay_encendido
    id: encender

  - platform: state
    entity_id: !input sensor_presencia
    from: !input valor_encendido
    to: !input valor_apagado
    for:
      seconds: !input delay_apagado
    id: apagar

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: encender
          - condition: state
            entity_id: !input variable_estado
            state: "off"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input variable_estado

          - service: light.turn_on
            target:
              entity_id: !input luz

          - delay:
              seconds: 4

          - service: climate.turn_on
            target:
              entity_id: !input clima

          - delay:
              seconds: 2

          - service: climate.set_temperature
            data:
              temperature: 24
              hvac_mode: cool
            target:
              entity_id: !input clima

          - delay:
              seconds: 2

          - service: climate.set_fan_mode
            data:
              fan_mode: auto_low
            target:
              entity_id: !input clima

          - delay:
              seconds: 5

      - conditions:
          - condition: trigger
            id: apagar
          - condition: state
            entity_id: !input variable_estado
            state: "on"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input variable_estado

          - service: light.turn_off
            target:
              entity_id: !input luz

          - delay:
              seconds: 2

          - service: climate.turn_off
            target:
              entity_id: !input clima

          - delay:
              seconds: 2

mode: single
